# Generated by Django 5.0.6 on 2024-06-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_remove_author_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='User',
        ),
    ]
