# Generated by Django 5.0.6 on 2024-07-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
